version: '3.9'

services:
  mysql:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:?err}
      MYSQL_HOST: 127.0.0.1
    healthcheck:
      test: "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD:?err} -e \"show databases\""
      interval: 1s
      retries: 120

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
      - "${RABBITMQ_SERVER_PORT:-5672}:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  
  open-api:
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    container_name: open-api
    ports:
      - "${OPENAPI_SERVER_PORT:?err}:${OPENAPI_SERVER_PORT}"
      # - "${OPENAPI_SERVER_PORT_SSL:?err}:${OPENAPI_SERVER_PORT_SSL}"
    build: 
      context: /${PATH_OPEN_API}
      dockerfile: Dockerfile
      target: development
    volumes:
      - "${SSL_FILE_PATH:?err}:${SSL_FILE_PATH}"
    environment:
      - HOST=${OPEN_API_HOST:?err}
      - PORT=${OPENAPI_SERVER_PORT:?err}

      - SSL_SERVER_NAME=${OPEN_API_HOST:?err}
      # - SSL_PORT=${OPENAPI_SERVER_PORT_SSL:?err}
      - SSL_CERTIFICATE=${SSL_CERTIFICATE:?err}
      - SSL_KEY=${SSL_KEY:?err}
      - SSL_PEM=${SSL_PEM:?err}

      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_OPEN_API}

      - DEV_HOST=http://${DEV_HOST:?err}
      - DEV_PORT=${DEV_PORT:?err}
      - DEV_VERSION=${DEV_VERSION:?err}

      - ID=${SETUP_ID:?err}
      - KEY=${SETUP_KEY:?err}

      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_MANAGEMENT_PORT=${RABBITMQ_MANAGEMENT_PORT:-15672}
      - RABBITMQ_SERVER_PORT=${RABBITMQ_SERVER_PORT:-5672}
      - RABBITMQ_EXCHANGE_NAME=${RABBITMQ_EXCHANGE_NAME:-DEKU_CLUSTER_SMS}
      - RABBITMQ_EXCHANGE_TYPE=${RABBITMQ_EXCHANGE_TYPE:-topic}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME:-OUTGOING_SMS}

      - RABBITMQ_SSL_ACTIVE=${RABBITMQ_SSL_ACTIVE}
      - RABBITMQ_SSL_HOST=${RABBITMQ_SSL_HOST}
      # - RABBITMQ_SSL_PORT=${RABBITMQ_SERVER_PORT_SSL}
      - RABBITMQ_SSL_CACERT=${SSL_PEM}
      - RABBITMQ_SSL_CRT=${SSL_CERTIFICATE}
      - RABBITMQ_SSL_KEY=${SSL_KEY}